const LEAGUE_ID = 13174;
const state = { league:null, bootstrap:null, managers:null, articles:null, champions:null, currentGw:1, liveCache:new Map() };
const qs=(s,r=document)=>r.querySelector(s);
const qsa=(s,r=document)=>[...r.querySelectorAll(s)];
function asArray(v){if(Array.isArray(v))return v;if(!v||typeof v!=='object')return[];for(const k of ['results','data','items','picks','elements'])if(Array.isArray(v[k]))return v[k];return Object.values(v).filter(x=>x&&typeof x==='object'&&!Array.isArray(x))}
function num(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f}
function esc(v=''){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function dateHr(v){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat('hr-HR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d)}
function timeHr(v){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('hr-HR',{hour:'2-digit',minute:'2-digit'}).format(d)}
async function fetchJson(url,options={}){const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'},...options});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);const t=r.headers.get('content-type')||'';if(!t.includes('json'))throw new Error(`Expected JSON from ${url}`);return r.json()}
async function loadCore(){if(state.league&&state.bootstrap)return state;const [league,bootstrap,managers,articles,champions]=await Promise.all([fetchJson('/api/league'),fetchJson('/api/bootstrap'),fetchJson('/data/managers.json').catch(()=>({managers:[]})),fetchJson('/data/articles.json').catch(()=>({articles:[]})),fetchJson('/data/champions.json').catch(()=>({champions:[]}))]);Object.assign(state,{league,bootstrap,managers,articles,champions});state.currentGw=deriveCurrentGw();return state}
function deriveCurrentGw(){const events=asArray(state.bootstrap?.events),cur=events.find(e=>e.is_current);if(cur)return num(cur.id,1);const next=events.find(e=>e.is_next);if(next)return num(next.id,1);const ms=asArray(state.league?.matches),live=ms.filter(m=>!m.finished&&(num(m.league_entry_1_points)||num(m.league_entry_2_points))).map(m=>num(m.event)).filter(Boolean);if(live.length)return Math.min(...live);const done=ms.filter(m=>m.finished).map(m=>num(m.event)).filter(Boolean);return done.length?Math.max(...done):1}
function currentEventInfo(gw=state.currentGw){return asArray(state.bootstrap?.events).find(e=>num(e.id)===num(gw))||{}}
function blockForGw(gw){const b=[{id:1,start:1,end:7,label:'GW 1–7'},{id:2,start:8,end:14,label:'GW 8–14'},{id:3,start:15,end:21,label:'GW 15–21'},{id:4,start:22,end:28,label:'GW 22–28'},{id:5,start:29,end:35,label:'GW 29–35'}];return b.find(x=>gw>=x.start&&gw<=x.end)||(gw>35?b[4]:b[0])}
function managerProfiles(){return asArray(state.managers?.managers)}
function entryRecords(){const profiles=managerProfiles();return asArray(state.league?.league_entries).map(e=>{const team=e.entry_name||e.name||e.team_name||`Ekipa ${e.id??''}`;const full=[e.player_first_name,e.player_last_name].filter(Boolean).join(' ').trim();const profile=profiles.find(p=>(p.team&&p.team.toLowerCase()===String(team).toLowerCase())||(p.name&&full&&p.name.toLowerCase()===full.toLowerCase()));return{leagueEntryId:num(e.id??e.league_entry??e.league_entry_id,-1),entryId:num(e.entry_id??e.entry??e.id,-1),team,manager:full||profile?.name||e.player_name||'—',raw:e,profile}})}
function entryMap(){return new Map(entryRecords().map(e=>[e.leagueEntryId,e]))}
function standingsRows(){const entries=entryMap();const rows=asArray(state.league?.standings).map((r,i)=>{const id=num(r.league_entry??r.id??r.entry_id,-1),e=entries.get(id)||{team:`Ekipa ${id}`,manager:'—'};return{id,team:e.team,manager:e.manager,rank:num(r.rank,i+1),played:num(r.matches_played??r.played??r.p,0),won:num(r.matches_won??r.won??r.w,0),drawn:num(r.matches_drawn??r.drawn??r.d,0),lost:num(r.matches_lost??r.lost??r.l,0),h2h:num(r.total??r.points??r.h2h_points,0),for:num(r.points_for??r.score??r.fantasy_points,0),against:num(r.points_against??r.points_against_total??r.against,0)}});rows.sort((a,b)=>a.rank-b.rank||b.h2h-a.h2h||b.for-a.for);return rows}
function matchesForGw(gw){return asArray(state.league?.matches).filter(m=>num(m.event)===num(gw))}
function matchStatus(m){if(m.finished)return{label:'FT',cls:'done'};if(num(m.league_entry_1_points)>0||num(m.league_entry_2_points)>0)return{label:'LIVE',cls:'live'};return{label:'USKORO',cls:'upcoming'}}
function matchUrl(m){return `/match.html?gw=${encodeURIComponent(num(m.event))}&a=${encodeURIComponent(num(m.league_entry_1))}&b=${encodeURIComponent(num(m.league_entry_2))}`}
function scoreMapForBlock(block,throughGw=block.end){const out=new Map(),add=(id,gw,pts)=>{id=num(id,-1);gw=num(gw,-1);if(id<0||gw<block.start||gw>block.end||gw>throughGw)return;if(!out.has(id))out.set(id,new Map());out.get(id).set(gw,num(pts))};for(const m of asArray(state.league?.matches)){const gw=num(m.event);if(gw<block.start||gw>block.end||gw>throughGw)continue;add(m.league_entry_1,gw,m.league_entry_1_points);add(m.league_entry_2,gw,m.league_entry_2_points)}return out}
function miniRows(block,throughGw=Math.min(state.currentGw,block.end)){const entries=entryRecords(),scores=scoreMapForBlock(block,throughGw);const rows=entries.map(e=>{const by=scores.get(e.leagueEntryId)||new Map(),vals=[...by.entries()].filter(([gw])=>gw<=throughGw).map(([,v])=>v);return{id:e.leagueEntryId,team:e.team,manager:e.manager,total:vals.reduce((a,b)=>a+b,0),max:vals.length?Math.max(...vals):0,played:vals.length}}).sort((a,b)=>b.total-a.total||b.max-a.max||a.team.localeCompare(b.team,'hr'));let last=null,rank=0;rows.forEach((r,i)=>{const k=`${r.total}:${r.max}`;if(k!==last)rank=i+1;r.rank=rank;last=k});return rows}
async function getLive(gw){if(state.liveCache.has(gw))return state.liveCache.get(gw);const d=await fetchJson(`/api/live/${gw}`).catch(e=>{console.warn('Live API error',e);return{elements:{}}});state.liveCache.set(gw,d);return d}
function livePointMap(live){const src=live?.elements;if(Array.isArray(src))return new Map(src.map(el=>[num(el?.id??el?.element,-1),num(el?.stats?.total_points??el?.total_points??el?.points,0)]).filter(([id])=>id>=0));if(src&&typeof src==='object')return new Map(Object.entries(src).map(([key,el])=>[num(el?.id??el?.element??key,-1),num(el?.stats?.total_points??el?.total_points??el?.points,0)]).filter(([id])=>id>=0));return new Map()}
function playerMap(){return new Map(asArray(state.bootstrap?.elements).map(p=>[num(p.id),p]))}
function extractPicks(data){const direct=data?.picks||data?.elements||data?.lineup||data?.team||data?.squad;let a=asArray(direct);if(!a.length&&Array.isArray(data))a=data;return a.filter(x=>x&&(x.element!==undefined||x.element_id!==undefined||x.id!==undefined))}
function shameMetrics(){const entries=entryMap(),done=asArray(state.league?.matches).filter(m=>m.finished),s=[];done.forEach(m=>{s.push({id:num(m.league_entry_1),gw:num(m.event),pts:num(m.league_entry_1_points),oppPts:num(m.league_entry_2_points)});s.push({id:num(m.league_entry_2),gw:num(m.event),pts:num(m.league_entry_2_points),oppPts:num(m.league_entry_1_points)})});if(!s.length)return[];const low=s.slice().sort((a,b)=>a.pts-b.pts)[0],loss=s.filter(x=>x.pts<x.oppPts),big=loss.slice().sort((a,b)=>(b.oppPts-b.pts)-(a.oppPts-a.pts))[0],brave=loss.slice().sort((a,b)=>b.pts-a.pts)[0],by=new Map();s.forEach(x=>{if(!by.has(x.id))by.set(x.id,[]);by.get(x.id).push(x)});let streak={id:null,n:0,endGw:null};for(const[id,list]of by){list.sort((a,b)=>a.gw-b.gw);let c=0;for(const x of list){if(x.pts<x.oppPts){c++;if(c>streak.n)streak={id,n:c,endGw:x.gw}}else c=0}}const against=standingsRows().slice().sort((a,b)=>b.against-a.against)[0],name=id=>entries.get(id)||{team:'—'};return[low&&{icon:'↓',label:'Najniži GW rezultat',value:`${low.pts} pts`,sub:`${name(low.id).team} · GW${low.gw}`},big&&{icon:'☠',label:'Najveći poraz',value:`-${big.oppPts-big.pts}`,sub:`${name(big.id).team} · ${big.pts}:${big.oppPts} · GW${big.gw}`},brave&&{icon:'!',label:'Najviše bodova u porazu',value:`${brave.pts} pts`,sub:`${name(brave.id).team} · GW${brave.gw}`},streak.id!==null&&{icon:'⛓',label:'Najduži niz poraza',value:`${streak.n}`,sub:`${name(streak.id).team} · do GW${streak.endGw}`},against&&{icon:'◎',label:'Najviše primljenih bodova',value:`${against.against}`,sub:`${against.team} · fantasy bodovi protiv`}].filter(Boolean)}