function showToast(message,isError=false){const el=qs('#toast');if(!el)return;el.textContent=message;el.className=`toast show${isError?' error':''}`;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.className='toast',3200)}
function setGlobalGw(){const e=qs('#globalGw');if(e)e.textContent=`GW${state.currentGw}`}
function setActiveNav(){const p=document.body.dataset.page;qsa('.nav a[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===p))}
function initNav(){const b=qs('#mobileMenu'),n=qs('#mainNav');b?.addEventListener('click',()=>n?.classList.toggle('open'))}
async function initHome(){const block=blockForGw(state.currentGw),event=currentEventInfo();qs('#homeGw').textContent=`GW${state.currentGw}`;qs('#homeGwDates').textContent=event.deadline_time?`Deadline ${dateHr(event.deadline_time)} · ${timeHr(event.deadline_time)}`:'Aktualno kolo';qs('#homeMiniRange').textContent=block.label;renderLeagueTable('#homeLeagueTable',true);renderMiniTable('#homeMiniTable',block,Math.min(state.currentGw,block.end),true);renderMatchCards('#homeMatches',state.currentGw);renderLatestNews('#latestNews',3)}
async function initLeague(){renderLeagueTable('#leagueTable',false)}
async function initMini(){const s=qs('#miniSelect'),cur=blockForGw(state.currentGw);s.value=String(cur.id);const draw=()=>{const id=num(s.value,1),b={1:{id:1,start:1,end:7,label:'GW 1–7'},2:{id:2,start:8,end:14,label:'GW 8–14'},3:{id:3,start:15,end:21,label:'GW 15–21'},4:{id:4,start:22,end:28,label:'GW 22–28'},5:{id:5,start:29,end:35,label:'GW 29–35'}}[id],through=Math.min(state.currentGw,b.end);qs('#miniPageTitle').textContent=`Mini-prvenstvo ${b.id}`;qs('#miniPageRange').textContent=b.label;qs('#miniProgress').textContent=state.currentGw<b.start?'Još nije počelo':state.currentGw>b.end?'Završeno':`Trenutno GW${state.currentGw}`;renderMiniTable('#miniPageTable',b,through,false)};s.addEventListener('change',draw);draw()}
async function initFixtures(){const s=qs('#gwSelect');s.innerHTML=Array.from({length:38},(_,i)=>`<option value="${i+1}">GW ${i+1}</option>`).join('');s.value=String(state.currentGw);const draw=()=>{const gw=num(s.value,state.currentGw),host=qs('#fixtureGrid'),entries=entryMap(),ms=matchesForGw(gw);qs('#fixturesTitle').textContent=`GW ${gw}`;host.innerHTML=ms.map(m=>{const a=entries.get(num(m.league_entry_1))||{team:'—',manager:'—'},b=entries.get(num(m.league_entry_2))||{team:'—',manager:'—'},st=matchStatus(m);return`<a class="fixture-card" href="${matchUrl(m)}"><div class="fixture-row"><div class="fixture-team"><strong>${esc(a.team)}</strong><small>${esc(a.manager)}</small></div><div class="fixture-score">${num(m.league_entry_1_points)} : ${num(m.league_entry_2_points)}</div><div class="fixture-team"><strong>${esc(b.team)}</strong><small>${esc(b.manager)}</small></div></div><div class="fixture-meta"><span class="badge ${st.cls}">${st.label}</span><span>Otvori postave →</span></div></a>`}).join('')||'<div class="empty">Nema H2H parova za odabrano kolo.</div>'};s.addEventListener('change',draw);draw()}
async function initMatch(){const p=new URLSearchParams(location.search),gw=num(p.get('gw'),state.currentGw),aId=num(p.get('a'),-1),bId=num(p.get('b'),-1),entries=entryMap(),a=entries.get(aId),b=entries.get(bId);if(!a||!b){qs('#matchPage').innerHTML='<div class="notice">Meč nije pronađen. Vrati se na Fixtures & Results.</div>';return}const m=matchesForGw(gw).find(x=>(num(x.league_entry_1)===aId&&num(x.league_entry_2)===bId)||(num(x.league_entry_1)===bId&&num(x.league_entry_2)===aId));qs('#matchGw').textContent=`GW ${gw}`;qs('#matchTeamA').innerHTML=`<strong>${esc(a.team)}</strong><span>${esc(a.manager)}</span>`;qs('#matchTeamB').innerHTML=`<strong>${esc(b.team)}</strong><span>${esc(b.manager)}</span>`;if(m){const ah=num(m.league_entry_1)===aId,ap=ah?num(m.league_entry_1_points):num(m.league_entry_2_points),bp=ah?num(m.league_entry_2_points):num(m.league_entry_1_points),st=matchStatus(m);qs('#matchScore').textContent=`${ap} : ${bp}`;qs('#matchStatus').textContent=st.label;qs('#matchStatus').className=`badge ${st.cls}`}const live=await getLive(gw);await Promise.all([renderSquad(qs('#squadA'),a,gw,live),renderSquad(qs('#squadB'),b,gw,live)])}
async function boot(){initNav();setActiveNav();try{await loadCore();setGlobalGw();const p=document.body.dataset.page;if(p==='home')await initHome();if(p==='league')await initLeague();if(p==='mini')await initMini();if(p==='fixtures')await initFixtures();if(p==='match')await initMatch();if(p==='editorial')renderLatestNews('#editorialNews',99);if(p==='fame')renderHallOfFame();if(p==='shame')renderShame('#shameGrid')}catch(e){console.error(e);showToast('FPL Draft API trenutno nije dostupan.',true);qsa('[data-loading]').forEach(x=>x.textContent='Podaci trenutno nisu dostupni.')}}
boot();